
version: '3'
services:
  backend:
    build: .
    image: myrulescardgame-backend-image
    container_name: myrulescardgame-backend
    restart: unless-stopped
    ports:
      - "5001:8080"
      - "5002:6002"
  coverage:
    build: ./code-coverage
    image: myrulescardgame-coverage-image
    container_name: myrulescardgame-coverage
    restart: unless-stopped
    ports:
      - "5003:5000"